laserMapping:
  ros__parameters:
    common:
      lid_topic: "/rslidar"
      imu_topic: "/imu"
      time_sync_en: false

    preprocess:
      lidar_type: 4
      scan_line: 128
      scan_rate: 10
      blind: 4

    mapping:
      acc_cov: 0.1
      gyr_cov: 0.1
      b_acc_cov: 0.0001
      b_gyr_cov: 0.0001
      fov_degree: 180
      det_range: 100.0
      extrinsic_est_en: false
      extrinsic_T: [1.494363791111, 0.000030061324, 0.903719820280]
      extrinsic_R: [-0.508348737805, 0.861029086113, -0.014507709641, -0.861100925582, -0.508429079519, -0.002251013466, -0.009314329527, 0.011348302346, 0.999892223842]
      extrinR_Gnss2Lidar: [1, 0, 0, 0, 1, 0, 0, 0, 1]
      extrinT_Gnss2Lidar: [0.0, 0.0, 0.0]

    publish:
      path_en: true
      scan_publish_en: true
      dense_publish_en: true
      scan_bodyframe_pub_en: true

    pcd_save:
      pcd_save_en: false
      interval: -1
